services:
  portaai_web:
    container_name: portaai_web
    build:
      context: .
      dockerfile: Dockerfile.app
    depends_on:
      - ollama
      - db
      - redis
    ports:
      - "5000:5000"
    networks:
      - portaai
    devices:
      - "/dev/video0:/dev/video0"  # Maps the webcam device
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              count: 1
              capabilities: ["gpu"]

  ollama:
    volumes:
      - ./ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0:11434
    networks:
      - portaai
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              count: 1
              capabilities: ["gpu"]

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - portaai
  
  db:
    container_name: db
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: portaai_user
      POSTGRES_PASSWORD: portaai_password
      POSTGRES_DB: portaai_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - portaai

networks:
  portaai:
    external: false

volumes:
  db_data: